require 'locomotive/relational_algebra/operators/comparisons/basic_comparison'
require 'locomotive/relational_algebra/operators/comparisons/equal'
require 'locomotive/relational_algebra/operators/comparisons/greater'
require 'locomotive/relational_algebra/operators/comparisons/greater_equal'
require 'locomotive/relational_algebra/operators/comparisons/less'
require 'locomotive/relational_algebra/operators/comparisons/less_equal'
